extends RefCounted

# Pure visual/local TEST combat. Canonical static values come from the live PPA
# source, generated by fetch_live_dungeon_combat_contract.py during CI.
# Does NOT write account, equipment, skills, inventory, progression or server.
const LIVE = preload("res://scripts/ppa_dungeon_combat_catalog_generated.gd")
const ARCHETYPES := ["ЖИВУЧИЙ", "БРОНИРОВАННЫЙ", "БЕРСЕРК"]
const ARCHETYPE_ATTACK := [21, 29, 46]

static func hero_stats(class_key: String, level: int) -> Dictionary:
    var key := class_key if LIVE.CLASS_BASE.has(class_key) else "gnome"
    var base: Dictionary = LIVE.CLASS_BASE[key]
    var lv := maxi(1, level)
    # Mirrors the deployed game's simpleClassStatsAtLevel(), no gear or ranks.
    return {
        "name":str(base.get("name", key)), "level":lv,
        "mhp":int(base["hp"])+(lv-1)*20,
        "mmp":int(base["mp"])+(lv-1)*10,
        "atk":int(base["atk"]), "def":int(base["def_"]),
        "range":int(base["range"]), "attack_speed":float(base["atkSpd"]),
        "crit":int(base["crit"]), "dodge":int(base["dodge"]),
        "crit_damage":int(base["critDmg"]), "attack_mode":str(base["attackMode"])
    }

static func active_skills(class_key: String) -> Array:
    var key := class_key if LIVE.CLASS_SKILLS.has(class_key) else "gnome"
    return LIVE.CLASS_SKILLS[key]["active"]

static func mob_stats(level: int, room_ordinal: int) -> Dictionary:
    if level < 1 or level > 60:
        return {}
    var base_level := ((level - 1) % 20) + 1
    var base: Dictionary = LIVE.MOB_TABLE[base_level - 1]
    var stats := {
        "level":level, "base_level":base_level, "name":str(base["n"]),
        "mhp":int(base["hp"]), "atk":int(base["atk"]),
        "def":int(base["def"]), "xp":int(base["xp"]),
        "damage_type":str(base.get("damageType", "physical")),
        "archetype":""
    }
    if level<=20:
        # The PPA's additional 11–20 defense curve is not a new mob kind.
        if level >= 11:
            stats["def"] += 3 if level<=12 else (4 if level<=14 else (5 if level<=16 else (6 if level<=18 else 7)))
        return stats
    var kind := posmod(room_ordinal, 3)
    var ref_level := base_level + 20
    var low := 900.0
    var high := 1300.0
    var fraction := 0.0
    if ref_level<=25:
        fraction=float(ref_level-21)/4.0
    elif ref_level<=30:
        low=1300.0
        high=1800.0
        fraction=float(ref_level-26)/4.0
    elif ref_level<=35:
        low=2000.0
        high=3000.0
        fraction=float(ref_level-31)/4.0
    else:
        low=3000.0
        high=4500.0
        fraction=float(ref_level-36)/4.0
    var hp_base := lerpf(low,high,clampf(fraction,0.0,1.0))
    var hp_mul := 1.10 if kind==0 else (0.92 if kind==2 else 1.0)
    var ref_hp := roundi(clampf(hp_base*hp_mul,low,high)) + (250 if ref_level<=30 else 210)
    var def_steps := maxi(0,int(floor(float(ref_level-30)/5.0)))
    var ref_def := roundi(float(maxi(20,ref_level-1))*(1.0+float(def_steps)*0.05))
    if ref_level>=30:
        ref_def+=6
    if kind==1:
        ref_def*=2
    var base_attack: int = ARCHETYPE_ATTACK[kind]
    if level<=40:
        # The deployed PPA uses +2210 (not +210) for 31–40 in its
        # applyDungeon21MobStats runtime, and +43 DEF at 31–40.
        stats["mhp"] = ref_hp + (2000 if level>=31 else 0)
        stats["def"] = ref_def + (43 if level>=31 else 0)
        stats["atk"] = base_attack
    else:
        # 41–60 calculates from reference 21–40 stats BEFORE extra 21–40
        # overrides. Mirrors applyDungeon41MobStats() in current live PPA.
        stats["mhp"] = roundi(float(ref_hp)*1.10)+10000
        stats["def"] = roundi(float(ref_def)*1.07)+160
        stats["atk"] = roundi(float(base_attack)*1.13)+50
    stats["archetype"] = ARCHETYPES[kind]
    return stats

# This formula is intentionally local TEST combat, not the production server
# damage formula (equipment/runes/skill rank context is not connected).
static func preview_damage(attack: int, defense: int, multiplier: float = 1.0) -> int:
    return maxi(1,roundi(float(attack)*multiplier - float(defense)*0.25))
